### ISSUE TITLE
Protect from forgery

### ISSUE THREAD

**Issue by mauriciopasquier** [FAO-GSP/sisinta-core#1]
From Devise

>  For Rails 5, note that protect_from_forgery is no longer prepended to the before_action chain, so if you have set authenticate_user before protect_from_forgery, your request will result in "Can't verify CSRF token authenticity." To resolve this, either change the order in which you call them, or use protect_from_forgery prepend: true.

I got into this error by starting the app without memcached online.

**Comment by yigini** [comment]
so? :)

**Comment by mauriciopasquier** [comment]
This is fixed!
